[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.15",
    "pypdf>=5.2.0",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.0.1",
]
